"""
Pydantic models for the research agent.

All state fields, tool inputs/outputs, and API payloads are typed here.
M10 additions:
  - ClarifyingQuestion: typed question object from clarification_node
  - AgentState: added clarifying_questions + user_answers fields
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, Annotated
from pydantic import BaseModel, Field
from datetime import datetime
import operator


# ============================================================================
# PAPER MODELS
# ============================================================================

class PaperMetadata(BaseModel):
    arxiv_id: str
    title: str
    authors: List[str]
    abstract: str
    published_date: str
    pdf_url: str
    categories: List[str] = []


class CitationData(BaseModel):
    citation_count: int = 0
    influential_citation_count: int = 0
    h_index: int = 0


class RankedPaper(BaseModel):
    arxiv_id: str
    title: str
    authors: List[str]
    abstract: str
    published_date: str
    url: str
    citation_count: int = 0
    relevance_score: float = 0.5
    recency_score: float = 0.5
    composite_rank_score: float = 0.0
    rank_position: int = 1


# ============================================================================
# STRATEGY + GAP MODELS
# ============================================================================

class ResearchStrategy(BaseModel):
    topics: List[str] = Field(description="3-5 specific topics to search")
    date_range_start: Optional[str] = Field(None, description="YYYY-MM-DD")
    date_range_end: Optional[str] = Field(None, description="YYYY-MM-DD")
    ranking_criteria: str = Field(default="balanced")
    search_depth: str = Field(default="balanced")


class KnowledgeGap(BaseModel):
    gap_id: str = Field(description="Unique identifier for this gap, e.g. 'gap_1'")
    description: str = Field(description="What is missing from current research")
    priority: int = Field(default=1, description="1=highest priority")
    resolved: bool = Field(default=False)


# ============================================================================
# M10 — CLARIFYING QUESTION MODEL (new)
# ============================================================================

class ClarifyingQuestion(BaseModel):
    """
    A typed clarifying question generated by clarification_node.

    Using typed objects instead of freeform strings:
      - API can filter by question_type (surface constraints to user first)
      - human_input_node can route answers to the right state field
        (constraint/preference → user_preferences; clarification → history only)
      - required=True questions block the agent from continuing without an answer
      - gap_id links the question back to the KnowledgeGap that triggered it
    """
    question: str = Field(description="The question text to show the user")
    gap_id: str = Field(description="Which KnowledgeGap this question addresses")
    question_type: str = Field(
        description="'preference' | 'constraint' | 'clarification'"
    )
    required: bool = Field(
        default=True,
        description="If True, agent cannot continue without this answer"
    )


# ============================================================================
# RESEARCH BRIEF
# ============================================================================

class ResearchBrief(BaseModel):
    executive_summary: str = ""
    key_findings: List[str] = []
    remaining_gaps: List[str] = []
    next_steps: List[str] = []
    iterations_taken: int = 0
    total_papers_found: int = 0
    top_papers: List[RankedPaper] = []


# ============================================================================
# AGENT STATE
# ============================================================================

class AgentState(BaseModel):
    """
    Full state of the research agent.

    LangGraph uses field annotations to decide reducer behavior:
      Annotated[List[X], operator.add]  → append (never overwrite)
      Optional[X]                       → plain overwrite

    M10 additions:
      clarifying_questions: typed ClarifyingQuestion objects from clarification_node
      user_answers:         injected by update_state() during HITL resume
    """

    # ── Core ──────────────────────────────────────────────────────────────────
    goal: str = ""
    status: str = "initialized"
    iteration_count: int = 0
    last_error: Optional[str] = None

    # ── Papers (append-only via reducer) ──────────────────────────────────────
    papers: Annotated[List[RankedPaper], operator.add] = []
    ranked_papers: Optional[List[RankedPaper]] = None       # overwrite each iteration

    # ── Strategy + Gaps ───────────────────────────────────────────────────────
    strategy: Optional[ResearchStrategy] = None
    gaps: Annotated[List[KnowledgeGap], operator.add] = []

    # ── Memory ────────────────────────────────────────────────────────────────
    conversation_history: Annotated[List[Dict[str, Any]], operator.add] = []
    summarized_history: str = ""                            # compressed archive
    user_preferences: Optional[Dict[str, Any]] = None
    failed_searches: Annotated[List[str], operator.add] = []
    search_queries_tried: Annotated[List[str], operator.add] = []

    # ── HITL (M10) ────────────────────────────────────────────────────────────
    clarifying_questions: Optional[List[ClarifyingQuestion]] = None
    # user_answers is injected via update_state() during resume.
    # human_input_node reads it, merges into history, then clears it.
    user_answers: Optional[List[Dict[str, Any]]] = None

    # ── Output ────────────────────────────────────────────────────────────────
    research_brief: Optional[ResearchBrief] = None
